// @flow
export const START_METRONOME: 'START_METRONOME' = 'START_METRONOME';
export const STOP_METRONOME: 'STOP_METRONOME' = 'STOP_METRONOME';
export const METRONOME_TICKS: 'METRONOME_TICKS' = 'METRONOME_TICKS';
export const INCREMENT_BPM: 'INCREMENT_BPM' = 'INCREMENT_BPM';
export const INCREMENT_ACCENT_INTERVAL: 'INCREMENT_ACCENT_INTERVAL' = 'INCREMENT_ACCENT_INTERVAL';
export const DECREMENT_BPM: 'DECREMENT_BPM' = 'DECREMENT_BPM';
export const DECREMENT_ACCENT_INTERVAL: 'DECREMENT_ACCENT_INTERVAL' = 'DECREMENT_ACCENT_INTERVAL';
export const CHANGE_ACCENT_INTERVAL: 'CHANGE_ACCENT_INTERVAL' = 'CHANGE_ACCENT_INTERVAL';
export const CHANGE_BPM_INPUT: 'CHANGE_BPM_INPUT' = 'CHANGE_BPM_INPUT';
export const VALIDATE_BPM_INPUT: 'VALIDATE_BPM_INPUT' = 'VALIDATE_BPM_INPUT';

export const ODD_TIME_BPM_INPUT: 'ODD_TIME_BPM_INPUT' = 'ODD_TIME_BPM_INPUT';
export const ODD_TIME_ACCENT_INPUT: 'ODD_TIME_ACCENT_INPUT' = 'ODD_TIME_ACCENT_INPUT';
export const ODD_TIME_DURATION_INPUT: 'ODD_TIME_DURATION_INPUT' = 'ODD_TIME_DURATION_INPUT';
export const ADD_ODD_TIME_ITEM: 'ADD_ODD_TIME_ITEM' = 'ADD_ODD_TIME_ITEM';
export const REMOVE_ODD_TIME_ITEM: 'REMOVE_ODD_TIME_ITEM' = 'REMOVE_ODD_TIME_ITEM';
export const START_ODD_TIME_METRONOME = 'START_ODD_TIME_METRONOME';
export const STOP_ODD_TIME_METRONOME = 'STOP_ODD_TIME_METRONOME';
export const ODD_TIME_METRONOME_TICKS = 'ODD_TIME_METRONOME_TICKS';
export const CHANGE_ODD_TIME_SPEED_FACTOR = 'CHANGE_ODD_TIME_SPEED_FACTOR';
export const VALIDATE_ODD_TIME_SPEED_FACTOR = 'VALIDATE_ODD_TIME_SPEED_FACTOR';
